@Library('my-shared-library') _

pipeline {
    agent any

    environment {
        IMAGE_NAME = "my-dockerhub-user/myapp"
        IMAGE_TAG = "v1.0.${env.BUILD_NUMBER}"
        MANIFESTS_PATH = "k8s-manifests"
        MANIFESTS_REPO_PATH = "/var/lib/jenkins/manifests"
    }

    stages {
        stage('Build Image') {
            steps {
                buildImage(IMAGE_NAME, IMAGE_TAG)
            }
        }
        stage('Scan Image') {
            steps {
                scanImage(IMAGE_NAME, IMAGE_TAG)
            }
        }
        stage('Push Image') {
            steps {
                pushImage(IMAGE_NAME, IMAGE_TAG)
            }
        }
        stage('Delete Image Locally') {
            steps {
                deleteLocalImage(IMAGE_NAME, IMAGE_TAG)
            }
        }
        stage('Update Manifests') {
            steps {
                updateManifests(MANIFESTS_PATH, IMAGE_NAME, IMAGE_TAG)
            }
        }
        stage('Push Manifests') {
            steps {
                pushManifests(MANIFESTS_REPO_PATH)
            }
        }
    }
}
